{config, ...}:

let
  dataDir = "/var/lib/zigbee2mqtt";
  internal-ip = "192.168.111.11";
  webport = 8521;
in
{
  # Only the three actual secrets (mqtt credentials + zigbee network key) are
  # encrypted, as ZIGBEE2MQTT_CONFIG_* assignments. Everything else lives in
  # services.zigbee2mqtt.settings below and is generated by the module — the
  # whole configuration.yaml used to be one opaque sops blob, which meant no
  # setting could be reviewed or changed without decrypting it.
  sops.secrets."cake-zigbee2mqtt-env".restartUnits = [ "zigbee2mqtt.service" ];

  services.udev.extraRules = ''
    SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", SYMLINK+="cc2531", MODE="0660", GROUP="dialout"
  '';

  services.zigbee2mqtt = {
    enable = true;
    inherit dataDir;
    settings = {
      version = 5;
      mqtt = {
        base_topic = "/ham/zigbee_cake";
        client_id = "zigbee2mqtt_cake";
        include_device_information = true;
        server = "mqtt://${internal-ip}:1883";
        # user + password: cake-zigbee2mqtt-env
      };
      # sets DeviceAllow in systemd service
      serial = {
        port = "/dev/cc2531";
        adapter = "ember";
        rtscts = false;
      };
      frontend = {
        enabled = true;
        port = webport;
      };
      homeassistant.enabled = true;
      availability = {
        enabled = true;
        active.timeout = 720;
        passive.timeout = 4320;
      };
      advanced = {
        elapsed = true;
        last_seen = "ISO_8601";
        # journal only, no second copy under ${dataDir}/log
        log_output = [ "console" ];
        # every device report is logged as a full JSON payload at info level;
        # other namespaces stay at info
        log_namespaced_levels."z2m:mqtt" = "warning";
        # network identity of the running mesh — changing any of these re-pairs
        # every device, so they are pinned to what the network was formed with
        channel = 20;
        pan_id = 26820;
        ext_pan_id = [ 183 18 138 129 84 132 152 215 ];
        # network_key: cake-zigbee2mqtt-env
      };
    };
  };

  services.nginx.recommendedProxySettings = true;
  services.nginx.virtualHosts."zigbee_cake" = {
    serverAliases = [ "zigbee_cake.lan" ];
    locations."/".proxyPass = "http://localhost:${toString webport}";
    locations."/api".proxyPass = "http://localhost:${toString webport}";
    locations."/api".proxyWebsockets = true;
    extraConfig = ''
      if ( $server_addr != "${internal-ip}" ) {
        return 403;
      }
    '';
  };

  state = [ "${dataDir}/devices.yaml" "${dataDir}/state.json" ];

  # configuration.yaml used to be a sops symlink into /run/secrets; the module's
  # ExecStartPre would now try to cp through it and fail. The file is
  # regenerated on every service start, so dropping it here is free.
  systemd.tmpfiles.rules = [ "r ${dataDir}/configuration.yaml" ];

  systemd.services.zigbee2mqtt = {
    serviceConfig.EnvironmentFile = config.sops.secrets."cake-zigbee2mqtt-env".path;
    after = [
      "home-assistant.service"
      "mosquitto.service"
      # "network-online.target"
    ];
  };
}
