{config, ...}:

let
  dataDir = "/var/lib/zigbee2mqtt";
  internal-ip = "192.168.111.11";
  webport = 8521;
in
{
  # Only the three actual secrets (mqtt credentials + zigbee network key) are
  # encrypted, as ZIGBEE2MQTT_CONFIG_* assignments. Everything else lives in
  # services.zigbee2mqtt.settings below and is generated by the module — the
  # whole configuration.yaml used to be one opaque sops blob, which meant no
  # setting could be reviewed or changed without decrypting it.
  sops.secrets."omo-zigbee2mqtt-env".restartUnits = [ "zigbee2mqtt.service" ];

  # symlink the zigbee controller
  #services.udev.extraRules = ''
  #  SUBSYSTEM=="tty", ATTRS{idVendor}=="0451", ATTRS{idProduct}=="16a8", SYMLINK+="cc2531", MODE="0660", GROUP="dialout"
  #'';

  # /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_21_CC_45_BD-if00-port0
  services.udev.extraRules = ''
    SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", SYMLINK+="cc2531", MODE="0660", GROUP="dialout"
  '';

  services.zigbee2mqtt = {
    enable = true;
    inherit dataDir;
    settings = {
      version = 5;
      mqtt = {
        base_topic = "/ham/zigbee";
        client_id = "zigbee2mqtt";
        include_device_information = true;
        server = "mqtt://${internal-ip}:1883";
        # user + password: omo-zigbee2mqtt-env
      };
      # sets DeviceAllow in systemd service
      serial = {
        port = "/dev/cc2531";
        adapter = "zstack";
      };
      frontend = {
        enabled = true;
        port = webport;
      };
      homeassistant = {
        enabled = true;
        legacy_action_sensor = true;
        experimental_event_entities = true;
      };
      availability = {
        enabled = true;
        active.timeout = 720;
        passive.timeout = 4320;
      };
      advanced = {
        elapsed = true;
        last_seen = "ISO_8601";
        # journal only, no second copy under ${dataDir}/log
        log_output = [ "console" ];
        # every device report is logged as a full JSON payload at info level,
        # ~17k journal lines a day; other namespaces stay at info
        log_namespaced_levels."z2m:mqtt" = "warning";
        # network identity of the running mesh — changing it re-pairs every
        # device. channel/ext_pan_id are left at the z2m defaults this network
        # was formed with.
        pan_id = 6755;
        # network_key: omo-zigbee2mqtt-env
      };
    };
  };

  services.nginx.recommendedProxySettings = true;
  services.nginx.virtualHosts."zigbee" = {
    serverAliases = [ "zigbee.lan" ];
    locations."/".proxyPass = "http://localhost:${toString webport}";
    locations."/api".proxyPass = "http://localhost:${toString webport}";
    locations."/api".proxyWebsockets = true;
    extraConfig = ''
      if ( $server_addr != "${internal-ip}" ) {
        return 403;
      }
    '';
  };

  state = [ "${dataDir}/devices.yaml" "${dataDir}/state.json" ];

  # configuration.yaml used to be a sops symlink into /run/secrets; the module's
  # ExecStartPre would now try to cp through it and fail. The file is
  # regenerated on every service start, so dropping it here is free.
  systemd.tmpfiles.rules = [ "r ${dataDir}/configuration.yaml" ];

  systemd.services.zigbee2mqtt = {
    serviceConfig.EnvironmentFile = config.sops.secrets."omo-zigbee2mqtt-env".path;
    after = [
      "home-assistant.service"
      "mosquitto.service"
      # "network-online.target"
    ];
  };
}
