# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."ghostwriter-collab-server" = {
    image = "ghcr.io/makefu/ghostwriter_production_collab_server:latest";
    environment = {
      "HASURA_ACTION_SECRET" = "ehyvb6Zk6Bh5an65N4eOZXknMIlMjNbs";
      "HASURA_GRAPHQL_ADMIN_SECRET" = "goAwDtnaOhfHhDeivHmYHw752fF1t9eF";
      "HASURA_GRAPHQL_SERVER_HOSTNAME" = "graphql_engine";
    };
    labels = {
      "name" = "ghostwriter_collab";
    };
    dependsOn = [
      "ghostwriter-django"
      "ghostwriter-graphql_engine"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=collab-server"
      "--network=ghostwriter_default"
    ];
  };
  systemd.services."podman-ghostwriter-collab-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-ghostwriter_default.service"
    ];
    requires = [
      "podman-network-ghostwriter_default.service"
    ];
    partOf = [
      "podman-compose-ghostwriter-root.target"
    ];
    wantedBy = [
      "podman-compose-ghostwriter-root.target"
    ];
  };
  virtualisation.oci-containers.containers."ghostwriter-django" = {
    image = "ghcr.io/makefu/ghostwriter_production_django:latest";
    environment = {
      "DATABASE_URL" = "postgres://postgres:eOjjAZ0UB4UTeJjtmMlYeRzbvKl9Bsnt@postgres:5432/ghostwriter";
      "DJANGO_ACCOUNT_ALLOW_REGISTRATION" = "false";
      "DJANGO_ACCOUNT_EMAIL_VERIFICATION" = "none";
      "DJANGO_ADMIN_URL" = "admin/";
      "DJANGO_ALLOWED_HOSTS" = "localhost 127.0.0.1 django nginx host.docker.internal ghostwriter.local";
      "DJANGO_CSRF_COOKIE_SECURE" = "true";
      "DJANGO_CSRF_TRUSTED_ORIGINS" = "";
      "DJANGO_DATE_FORMAT" = "d M Y";
      "DJANGO_JWT_SECRET_KEY" = "wph=*sGYVC9P69(d$ARKR>vJ&UNV@1M.";
      "DJANGO_MFA_ALWAYS_REVEAL_BACKUP_TOKENS" = "false";
      "DJANGO_QCLUSTER_NAME" = "soar";
      "DJANGO_SECRET_KEY" = "<UY>nqZM@%62Nf-4E0$=(oBvSnj4y!O>";
      "DJANGO_SECURE_SSL_REDIRECT" = "true";
      "DJANGO_SESSION_COOKIE_AGE" = "32400";
      "DJANGO_SESSION_COOKIE_SECURE" = "true";
      "DJANGO_SESSION_EXPIRE_AT_BROWSER_CLOSE" = "false";
      "DJANGO_SESSION_SAVE_EVERY_REQUEST" = "true";
      "DJANGO_SETTINGS_MODULE" = "config.settings.production";
      "DJANGO_SOCIAL_ACCOUNT_ALLOW_REGISTRATION" = "false";
      "DJANGO_SOCIAL_ACCOUNT_DOMAIN_ALLOWLIST" = "";
      "DJANGO_SOCIAL_ACCOUNT_LOGIN_ON_GET" = "false";
      "DJANGO_SUPERUSER_EMAIL" = "admin@ghostwriter.local";
      "DJANGO_SUPERUSER_PASSWORD" = "7P1sIX3TY5mU1uoi71biEy3WN7em2xa6";
      "DJANGO_SUPERUSER_USERNAME" = "admin";
      "HASURA_ACTION_SECRET" = "ehyvb6Zk6Bh5an65N4eOZXknMIlMjNbs";
      "HASURA_GRAPHQL_SERVER_HOSTNAME" = "graphql_engine";
      "HEALTHCHECK_DISK_USAGE_MAX" = "3";
      "HEALTHCHECK_MEM_MIN" = "100";
      "IPYTHONDIR" = "/app/.ipython";
      "MAILGUN_API_KEY" = "";
      "MAILGUN_DOMAIN" = "";
      "NO_PROXY" = "graphql_engine";
      "POSTGRES_DB" = "ghostwriter";
      "POSTGRES_HOST" = "postgres";
      "POSTGRES_PASSWORD" = "eOjjAZ0UB4UTeJjtmMlYeRzbvKl9Bsnt";
      "POSTGRES_PORT" = "5432";
      "POSTGRES_USER" = "postgres";
      "REDIS_URL" = "redis://redis:6379/0";
      "USE_DOCKER" = "yes";
      "WEB_CONCURRENCY" = "4";
    };
    volumes = [
      "ghostwriter_production_data:/app/ghostwriter/media:rw"
      "ghostwriter_production_staticfiles:/app/staticfiles:rw"
    ];
    cmd = [ "/start" ];
    labels = {
      "name" = "ghostwriter_django";
    };
    dependsOn = [
      "ghostwriter-postgres"
      "ghostwriter-redis"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=curl --insecure --fail http://localhost:8080/ || exit 1"
      "--health-interval=1m0s"
      "--health-retries=3"
      "--health-start-period=1m0s"
      "--health-timeout=30s"
      "--network-alias=django"
      "--network=ghostwriter_default"
    ];
  };
  systemd.services."podman-ghostwriter-django" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-ghostwriter_default.service"
      "podman-volume-ghostwriter_production_data.service"
      "podman-volume-ghostwriter_production_staticfiles.service"
    ];
    requires = [
      "podman-network-ghostwriter_default.service"
      "podman-volume-ghostwriter_production_data.service"
      "podman-volume-ghostwriter_production_staticfiles.service"
    ];
    partOf = [
      "podman-compose-ghostwriter-root.target"
    ];
    wantedBy = [
      "podman-compose-ghostwriter-root.target"
    ];
  };
  virtualisation.oci-containers.containers."ghostwriter-graphql_engine" = {
    image = "ghcr.io/makefu/ghostwriter_production_graphql:latest";
    environment = {
      "ACTIONS_URL_BASE" = "http://django:8000/api";
      "HASURA_ACTION_SECRET" = "ehyvb6Zk6Bh5an65N4eOZXknMIlMjNbs";
      "HASURA_GRAPHQL_ADMIN_SECRET" = "goAwDtnaOhfHhDeivHmYHw752fF1t9eF";
      "HASURA_GRAPHQL_AUTH_HOOK" = "http://django:8000/api/webhook";
      "HASURA_GRAPHQL_CONSOLE_ASSETS_DIR" = "/srv/console-assets";
      "HASURA_GRAPHQL_DATABASE_URL" = "postgres://postgres:eOjjAZ0UB4UTeJjtmMlYeRzbvKl9Bsnt@postgres:5432/ghostwriter";
      "HASURA_GRAPHQL_DEV_MODE" = "false";
      "HASURA_GRAPHQL_ENABLED_LOG_TYPES" = "startup, http-log, webhook-log, websocket-log, query-log";
      "HASURA_GRAPHQL_ENABLE_CONSOLE" = "false";
      "HASURA_GRAPHQL_ENABLE_TELEMETRY" = "false";
      "HASURA_GRAPHQL_INSECURE_SKIP_TLS_VERIFY" = "true";
      "HASURA_GRAPHQL_LOG_LEVEL" = "warn";
      "HASURA_GRAPHQL_METADATA_DIR" = "/metadata";
      "HASURA_GRAPHQL_MIGRATIONS_DIR" = "/migrations";
      "HASURA_GRAPHQL_SERVER_PORT" = "8080";
      "NO_PROXY" = "django";
    };
    volumes = [
      "/home/makefu/r/Ghostwriter/ssl:/etc/ssl/certs:rw"
    ];
    labels = {
      "name" = "ghostwriter_graphql";
    };
    dependsOn = [
      "ghostwriter-django"
      "ghostwriter-postgres"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=curl --insecure --fail http://graphql_engine:8080/healthz || exit 1"
      "--health-interval=5m0s"
      "--health-retries=3"
      "--health-start-period=1m0s"
      "--health-timeout=30s"
      "--network-alias=graphql_engine"
      "--network=ghostwriter_default"
    ];
  };
  systemd.services."podman-ghostwriter-graphql_engine" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-ghostwriter_default.service"
    ];
    requires = [
      "podman-network-ghostwriter_default.service"
    ];
    partOf = [
      "podman-compose-ghostwriter-root.target"
    ];
    wantedBy = [
      "podman-compose-ghostwriter-root.target"
    ];
  };
  virtualisation.oci-containers.containers."ghostwriter-nginx" = {
    image = "ghcr.io/makefu/ghostwriter_production_nginx:latest";
    environment = {
      "NO_PROXY" = "django,graphql_engine";
    };
    volumes = [
      "ghostwriter_production_data:/app/media:rw"
      "ghostwriter_production_staticfiles:/app/staticfiles:rw"
    ];
    ports = [
      "0.0.0.0:8180:80/tcp"
    ];
    labels = {
      "name" = "ghostwriter_nginx";
    };
    dependsOn = [
      "ghostwriter-django"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=curl --insecure --fail http://ghostwriter-nginx/ || exit 1"
      "--health-interval=1m0s"
      "--health-retries=3"
      "--health-start-period=1m0s"
      "--health-timeout=30s"
      "--network-alias=nginx"
      "--network=ghostwriter_default"
    ];
  };
  systemd.services."podman-ghostwriter-nginx" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-ghostwriter_default.service"
      "podman-volume-ghostwriter_production_data.service"
      "podman-volume-ghostwriter_production_staticfiles.service"
    ];
    requires = [
      "podman-network-ghostwriter_default.service"
      "podman-volume-ghostwriter_production_data.service"
      "podman-volume-ghostwriter_production_staticfiles.service"
    ];
    partOf = [
      "podman-compose-ghostwriter-root.target"
    ];
    wantedBy = [
      "podman-compose-ghostwriter-root.target"
    ];
  };
  virtualisation.oci-containers.containers."ghostwriter-postgres" = {
    image = "ghcr.io/makefu/ghostwriter_production_postgres:latest";
    environment = {
      "NO_PROXY" = "django,graphql_engine";
      "POSTGRES_DB" = "ghostwriter";
      "POSTGRES_HOST" = "postgres";
      "POSTGRES_PASSWORD" = "eOjjAZ0UB4UTeJjtmMlYeRzbvKl9Bsnt";
      "POSTGRES_PORT" = "5432";
      "POSTGRES_USER" = "postgres";
    };
    volumes = [
      "ghostwriter_production_postgres_data:/var/lib/postgresql/data:rw"
      "ghostwriter_production_postgres_data_backups:/backups:rw"
    ];
    labels = {
      "name" = "ghostwriter_postgres";
    };
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"
      "--health-interval=5m0s"
      "--health-retries=3"
      "--health-start-period=1m0s"
      "--health-timeout=30s"
      "--network-alias=postgres"
      "--network=ghostwriter_default"
    ];
  };
  systemd.services."podman-ghostwriter-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-ghostwriter_default.service"
      "podman-volume-ghostwriter_production_postgres_data.service"
      "podman-volume-ghostwriter_production_postgres_data_backups.service"
    ];
    requires = [
      "podman-network-ghostwriter_default.service"
      "podman-volume-ghostwriter_production_postgres_data.service"
      "podman-volume-ghostwriter_production_postgres_data_backups.service"
    ];
    partOf = [
      "podman-compose-ghostwriter-root.target"
    ];
    wantedBy = [
      "podman-compose-ghostwriter-root.target"
    ];
  };
  virtualisation.oci-containers.containers."ghostwriter-queue" = {
    image = "ghcr.io/makefu/ghostwriter_production_queue:latest";
    environment = {
      "DATABASE_URL" = "postgres://postgres:eOjjAZ0UB4UTeJjtmMlYeRzbvKl9Bsnt@postgres:5432/ghostwriter";
      "DJANGO_ACCOUNT_ALLOW_REGISTRATION" = "false";
      "DJANGO_ACCOUNT_EMAIL_VERIFICATION" = "none";
      "DJANGO_ADMIN_URL" = "admin/";
      "DJANGO_ALLOWED_HOSTS" = "localhost 127.0.0.1 django nginx host.docker.internal ghostwriter.local";
      "DJANGO_CSRF_COOKIE_SECURE" = "true";
      "DJANGO_CSRF_TRUSTED_ORIGINS" = "";
      "DJANGO_DATE_FORMAT" = "d M Y";
      "DJANGO_JWT_SECRET_KEY" = "wph=*sGYVC9P69(d$ARKR>vJ&UNV@1M.";
      "DJANGO_MFA_ALWAYS_REVEAL_BACKUP_TOKENS" = "false";
      "DJANGO_QCLUSTER_NAME" = "soar";
      "DJANGO_SECRET_KEY" = "<UY>nqZM@%62Nf-4E0$=(oBvSnj4y!O>";
      "DJANGO_SECURE_SSL_REDIRECT" = "true";
      "DJANGO_SESSION_COOKIE_AGE" = "32400";
      "DJANGO_SESSION_COOKIE_SECURE" = "true";
      "DJANGO_SESSION_EXPIRE_AT_BROWSER_CLOSE" = "false";
      "DJANGO_SESSION_SAVE_EVERY_REQUEST" = "true";
      "DJANGO_SETTINGS_MODULE" = "config.settings.production";
      "DJANGO_SOCIAL_ACCOUNT_ALLOW_REGISTRATION" = "false";
      "DJANGO_SOCIAL_ACCOUNT_DOMAIN_ALLOWLIST" = "";
      "DJANGO_SOCIAL_ACCOUNT_LOGIN_ON_GET" = "false";
      "DJANGO_SUPERUSER_EMAIL" = "admin@ghostwriter.local";
      "DJANGO_SUPERUSER_PASSWORD" = "7P1sIX3TY5mU1uoi71biEy3WN7em2xa6";
      "DJANGO_SUPERUSER_USERNAME" = "admin";
      "HASURA_ACTION_SECRET" = "ehyvb6Zk6Bh5an65N4eOZXknMIlMjNbs";
      "HASURA_GRAPHQL_SERVER_HOSTNAME" = "graphql_engine";
      "HEALTHCHECK_DISK_USAGE_MAX" = "3";
      "HEALTHCHECK_MEM_MIN" = "100";
      "IPYTHONDIR" = "/app/.ipython";
      "MAILGUN_API_KEY" = "";
      "MAILGUN_DOMAIN" = "";
      "NO_PROXY" = "graphql_engine";
      "POSTGRES_DB" = "ghostwriter";
      "POSTGRES_HOST" = "postgres";
      "POSTGRES_PASSWORD" = "eOjjAZ0UB4UTeJjtmMlYeRzbvKl9Bsnt";
      "POSTGRES_PORT" = "5432";
      "POSTGRES_USER" = "postgres";
      "REDIS_URL" = "redis://redis:6379/0";
      "USE_DOCKER" = "yes";
      "WEB_CONCURRENCY" = "4";
    };
    volumes = [
      "ghostwriter_production_data:/app/ghostwriter/media:rw"
      "ghostwriter_production_staticfiles:/app/staticfiles:rw"
    ];
    cmd = [ "/start-queue" ];
    labels = {
      "name" = "ghostwriter_queue";
    };
    dependsOn = [
      "ghostwriter-postgres"
      "ghostwriter-redis"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=curl --insecure --fail http://localhost:8080/ || exit 1"
      "--health-interval=5m0s"
      "--health-retries=3"
      "--health-start-period=1m0s"
      "--health-timeout=30s"
      "--network-alias=queue"
      "--network=ghostwriter_default"
    ];
  };
  systemd.services."podman-ghostwriter-queue" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-ghostwriter_default.service"
      "podman-volume-ghostwriter_production_data.service"
      "podman-volume-ghostwriter_production_staticfiles.service"
    ];
    requires = [
      "podman-network-ghostwriter_default.service"
      "podman-volume-ghostwriter_production_data.service"
      "podman-volume-ghostwriter_production_staticfiles.service"
    ];
    partOf = [
      "podman-compose-ghostwriter-root.target"
    ];
    wantedBy = [
      "podman-compose-ghostwriter-root.target"
    ];
  };
  virtualisation.oci-containers.containers."ghostwriter-redis" = {
    image = "ghcr.io/makefu/ghostwriter_production_redis:latest";
    labels = {
      "name" = "ghostwriter_redis";
    };
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=redis-cli --raw incr ping || exit 1"
      "--health-interval=5m0s"
      "--health-retries=3"
      "--health-start-period=1m0s"
      "--health-timeout=30s"
      "--network-alias=redis"
      "--network=ghostwriter_default"
    ];
  };
  systemd.services."podman-ghostwriter-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-ghostwriter_default.service"
    ];
    requires = [
      "podman-network-ghostwriter_default.service"
    ];
    partOf = [
      "podman-compose-ghostwriter-root.target"
    ];
    wantedBy = [
      "podman-compose-ghostwriter-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-ghostwriter_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f ghostwriter_default";
    };
    script = ''
      podman network inspect ghostwriter_default || podman network create ghostwriter_default
    '';
    partOf = [ "podman-compose-ghostwriter-root.target" ];
    wantedBy = [ "podman-compose-ghostwriter-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-ghostwriter_production_data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect ghostwriter_production_data || podman volume create ghostwriter_production_data
    '';
    partOf = [ "podman-compose-ghostwriter-root.target" ];
    wantedBy = [ "podman-compose-ghostwriter-root.target" ];
  };
  systemd.services."podman-volume-ghostwriter_production_postgres_data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect ghostwriter_production_postgres_data || podman volume create ghostwriter_production_postgres_data
    '';
    partOf = [ "podman-compose-ghostwriter-root.target" ];
    wantedBy = [ "podman-compose-ghostwriter-root.target" ];
  };
  systemd.services."podman-volume-ghostwriter_production_postgres_data_backups" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect ghostwriter_production_postgres_data_backups || podman volume create ghostwriter_production_postgres_data_backups
    '';
    partOf = [ "podman-compose-ghostwriter-root.target" ];
    wantedBy = [ "podman-compose-ghostwriter-root.target" ];
  };
  systemd.services."podman-volume-ghostwriter_production_staticfiles" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect ghostwriter_production_staticfiles || podman volume create ghostwriter_production_staticfiles
    '';
    partOf = [ "podman-compose-ghostwriter-root.target" ];
    wantedBy = [ "podman-compose-ghostwriter-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-ghostwriter-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
